language: node_js
sudo: required
dist: trusty
node_js:
  - '13'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules
before_script:
  - npm i -g polymer-cli@latest npm@latest
  - npm ci
script:
  - xvfb-run npm run test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test -- -s 'windows 10/microsoftedge@13' -s 'windows 10/microsoftedge@17' -s 'windows 8.1/internet explorer@11' -s 'os x 10.12/safari@10' -s 'macos 10.13/safari@11' -s 'macos 10.13/safari@12' -s 'Linux/chrome@41' -s 'windows 10/chrome@70' -s 'windows 10/firefox@62' -s 'windows 10/firefox@63'; fi

# Should you require setup for TravisCI with Sauce Labs? See https://www.youtube.com/watch?v=afy_EEq_4Go
